name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-project.yaml
    secrets: inherit
